### PR TITLE
Small fixes for relayer funder script

### LINKED ISSUE #732: Relayer funder is printing messages on multiple lines

### PR DESCRIPTION
**Pull request by tkporter**
* Format logs as JSON one-liners
* Catch errors so that any funding attempts after the error are still attempted, while still exiting with a non-zero exit code.
* Drive-by to change the Pushgateway to use `async/await` rather than `.then` for promises just to be more consistent with the rest of the codebase

This doesn't:
* Include the deployment to have this be used on testnet2/mainnet
* Change the cron schedule or desired relayer balances - this is mostly just bc I'm not confident the relayer funder has enough funds if we were to like 6x the desired relayer balances, and I figured we should get this fix out asap. We can do the cron schedule / desired relayer balance changes later-- I created https://github.com/abacus-network/abacus-monorepo/issues/742 to track this

Closes #732

### CODE REVIEW

File: typescript/infra/scripts/funding/fund-relayers-from-deployer.ts [hunk 1]
```diff
@@ -234,20 +240,52 @@ function submitFunderBalanceMetrics(balances: FunderBalance[]) {
...
+      ? (resp as any).statusCode
+      : 'unknown';
+  log(`Prometheus metrics pushed to PushGateway`, {
+    statusCode,
+    body,
+  });
+}
+
+function log(message: string, data?: any) {
+  logWithFunction(console.log, message, data);
```
Comment (mattiecnvr) [inline typescript/infra/scripts/funding/fund-relayers-from-deployer.ts:255]: Did you test this, afraid you might need to bind.

**Review by mattiecnvr — APPROVED** [review]

File: typescript/infra/scripts/funding/fund-relayers-from-deployer.ts (hunk 1 above)
Comment (tkporter) [reply typescript/infra/scripts/funding/fund-relayers-from-deployer.ts:255]: I did :)
```
$ ts-node ./scripts/funding/fund-relayers-from-deployer.ts -e testnet2
{"chain":"alfajores","funder":{"address":"0xfaD1C94469700833717Fa8a3017278BC1cA8031C","balance":"4.018313295","desiredRelayerBalance":"1"},"message":"Funding relayers on chain..."}
{"relayer":{"address":"0xe62512d3c303e0540ed0338da3f43d8f7b0a369e","identifier":"alias/abacus-testnet2-key-kovan-relayer","chain":"kovan"},"balance":"0.9899836205","message":"Relayer balance"}
{"relayer":{"address":"0xa9521dc08c963796f615817a20b2b2981def8bb5","identifier":"alias/abacus-testnet2-key-fuji-relayer","chain":"fuji"},"balance":"0.990055339","message":"Relayer balance"}
...
```
