### PR TITLE
Fix kathy message metric

### LINKED ISSUE #790: Kathy message sent counter resets akwardly
Because we are using a push metric that ends up being 1 or null, we are getting a really messy metric issue which I want to resolve by switching to a gauge for now of 0 or 1. Later if we are sending multiple messages we can go back to a count.

### PR DESCRIPTION
**Pull request by mattiecnvr**
Few things here,
1) use a gauge with 0/1 for true/false since the counter does not really work very well with a push metric when we are just reporting 1 or null.
2) switch to appending the metrics until the very end when we have everything in the register.
3) submit metrics on an interval so we don't have to wait until the process ends to get the metrics (kathy can take a while to run)

Closes #790

### CODE REVIEW

File: typescript/infra/scripts/helloworld/kathy.ts [hunk 1]
```diff
@@ -58,21 +65,24 @@ async function main() {
       };
       try {
         await sendMessage(app, source, destination);
-        messagesCount.labels({ ...labels, status: 'success' }).inc();
+        messagesSendStatus.labels({ ...labels }).set(1);
```
Comment (asaj) [inline typescript/infra/scripts/helloworld/kathy.ts:68]: Will we be able to set a useful alert based on this gauge? It seems that a failed message, which sets the gauge to zero, can be very quickly followed up by a successful message, which sets the gauge back to 1

Comment (mattiecnvr) [reply typescript/infra/scripts/helloworld/kathy.ts:68]: If there was a successful one do we care that the other failed? We really only care that it is succeeding. Also it only attempts to send one per cron interval which is generally quite high.

Comment (mattiecnvr) [reply typescript/infra/scripts/helloworld/kathy.ts:68]: > Yes, we care if any of them fail, 100% of Kathy messages should get delivered and we need to know if that's ever not the case.

well unless we decide to retry messages automatically we will still be able to alert on any failure as there is a large window where it will be reported as `0`.

> I'm not sure I follow, are you saying that Kathy only sends one message per cronjob? IIUC that's not true at the moment, Kathy appears to be configurable to send many messages.

We only send one message per cron job per origin/remote pairing. There are multiple messages sent but only one per that unique pairing, and the metric cardinality is defined by the pairing so that each origin/remote gets its own gauge value.

**Review by asaj — APPROVED** [review]
