### PR TITLE
Kathy message retrying

### LINKED ISSUE #837: Kathy should be more resilient to transient issues
Temporary issues like nonce reuse or provider issues cause "kathy" to be marked as failed. We should have a simple retry mechanism to smooth those over

### PR DESCRIPTION
**Pull request by mattiecnvr**
Merging this into the other kathy branch I have then will get that merged with main.

Closes #837

### CODE REVIEW

File: typescript/infra/scripts/helloworld/kathy.ts [hunk 1]
```diff
@@ -110,20 +116,30 @@ async function main() {
...
+      let attempt = 1, needToRetry = true;
+      attempt <= MAX_SEND_RETRIES + 1 && needToRetry;
+      ++attempt
+    ) {
+      const startTime = Date.now();
+      try {
+        await sendMessage(app, origin, destination, gasCalc);
+        needToRetry = false;
+        log('Message sent successfully', { origin, destination, attempt });
+        messagesSendCount.labels({ ...labels, status: 'success' }).inc();
```
Comment (yorhodes) [inline typescript/infra/scripts/helloworld/kathy.ts:130]: can we just break out of the loop instead of this `needToRetry`

File: typescript/infra/scripts/helloworld/kathy.ts [hunk 2]
```diff
@@ -155,14 +171,19 @@ async function sendMessage(
...
+    setTimeout(() => {
+      if (sent) {
+        reject(new Error('Timeout waiting for message receipt'));
+      } else {
+        reject(new Error('Timeout attempting to send message'));
+      }
+    }, MESSAGE_RECEIPT_TIMEOUT);
     app
       .sendHelloWorld(origin, destination, msg, value, (receipt) => {
+        sent = true;
```
Comment (yorhodes) [inline typescript/infra/scripts/helloworld/kathy.ts:186]: should we expose separate hooks? this `sent` usage seems brittle
have you tested this?

**Review by yorhodes — APPROVED** [review]

File: typescript/infra/scripts/helloworld/kathy.ts (hunk 1 above)
Comment (mattiecnvr) [reply typescript/infra/scripts/helloworld/kathy.ts:130]: If we did that we would not report the time taken.

Comment (mattiecnvr) [reply typescript/infra/scripts/helloworld/kathy.ts:130]: If we did that we would not report the time taken.

File: typescript/infra/scripts/helloworld/kathy.ts (hunk 2 above)
Comment (mattiecnvr) [reply typescript/infra/scripts/helloworld/kathy.ts:186]: I plan to test before we deploy, since it is only being used to give a better error message the consequence of it not working is somewhat low. I guess if we wanted a hook for when message is received too? Generally the whole thing kinda feels janky with the send waiting for receipt as well.
